# Generated by Django 4.0.6 on 2022-07-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('p1', 'Priority 1'), ('p2', 'Priority 2'), ('p3', 'Priority 3'), ('p4', 'Priority 4')], default='p4', max_length=5)),
            ],
        ),
    ]
