# Generated by Django 4.0.6 on 2022-07-29 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_tasksmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='task_happen_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
