# Generated by Django 4.0.6 on 2022-07-29 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_appuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='app_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='playground.appuser'),
            preserve_default=False,
        ),
    ]
