# Generated by Django 4.0.6 on 2022-08-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_tasksmodel_app_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='task_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
