# Generated by Django 4.1 on 2022-09-20 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_alter_tasksmodel_options_alter_appuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='birth_date',
        ),
    ]
