# Generated by Django 4.1.1 on 2022-10-01 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_remove_appuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodel',
            name='task_happen_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
