# Generated by Django 4.1.1 on 2022-10-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_alter_tasksmodel_task_happen_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodel',
            name='task_happen_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
