# Generated by Django 4.1.1 on 2022-10-02 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0015_commentsmodel_reactionsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='playground.tasksmodel'),
        ),
    ]
