# Generated by Django 4.1.1 on 2022-10-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0016_alter_commentsmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsmodel',
            old_name='user',
            new_name='task',
        ),
    ]
