# Generated by Django 4.1.1 on 2022-10-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0017_rename_user_commentsmodel_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='task',
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='playground.appuser'),
            preserve_default=False,
        ),
    ]
