# Generated by Django 4.1.1 on 2022-10-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0018_remove_commentsmodel_task_commentsmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsmodel',
            old_name='user',
            new_name='app_user',
        ),
    ]
