# Generated by Django 4.1.1 on 2022-10-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0020_alter_reactionsmodel_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactionsmodel',
            name='emoji',
            field=models.TextField(max_length=50),
        ),
    ]
