# Generated by Django 4.1.1 on 2022-10-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0022_alter_reactionsmodel_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactionsmodel',
            name='count',
        ),
    ]
